import { TrademarkRecord } from "./types";

export const DEFAULT_SEED_TRADEMARKS: TrademarkRecord[] = [
  {
    id: "355079",
    proprietor: "MD UZZAL GROUP LTD",
    proprietorAr: "مجموعة إم دي أوزال المحدودة",
    trademarkName: "MURASIL AL-GHARBIYA 1",
    trademarkNameAr: "مراسل الغربية ١",
    classNumber: 41,
    goodsServices: "News reporters services; news broadcasting; digital publishing; media photography and reporting services in the Western districts.",
    goodsServicesAr: "خدمات مراسلي الأخبار؛ بث الأخبار؛ النشر الرقمي؛ التصوير الإعلامي وخدمات إعداد التقارير في المناطق الغربية.",
    applicationDate: "2022-04-12",
    registrationDate: "2022-10-12",
    validityDate: "2032-10-12",
    address: "District 903, Al-Karrada, Baghdad, Iraq",
    addressAr: "حي ٩٠٣، الكرادة، بغداد، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1665532800000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "354120",
    proprietor: "AL-MANSOUR REFRESHMENTS LTD",
    proprietorAr: "شركة المنصور للمرطبات المحدودة",
    trademarkName: "TIGRIS BLUE WATER",
    trademarkNameAr: "مياه دجلة الزرقاء",
    classNumber: 32,
    goodsServices: "Mineral and aerated waters and other non-alcoholic beverages; fruit beverages and fruit juices; syrups and other preparations for making beverages.",
    goodsServicesAr: "المياه المعدنية والغازية وغيرها من المشروبات غير الكحولية؛ مشروبات الفواكه وعصائر الفواكه؛ الشراب وغيره من المستحضرات لصنع المشروبات.",
    applicationDate: "2021-09-05",
    registrationDate: "2022-03-15",
    validityDate: "2032-03-15",
    address: "Industrial Ward, Al-Mansour, Baghdad, Iraq",
    addressAr: "الحي الصناعي، المنصور، بغداد، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1647302400000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "356002",
    proprietor: "BABYLON TECHNOLOGY SYSTEMS",
    proprietorAr: "بابل لأنظمة التكنولوجيا",
    trademarkName: "UR SOFTWARE SUITE",
    trademarkNameAr: "باقة برمجيات أور",
    classNumber: 9,
    goodsServices: "Computer software systems; mobile applications; databases for registration; secure cryptographic authorization terminals.",
    goodsServicesAr: "أنظمة برامج الكمبيوتر؛ تطبيقات الهاتف المحمول؛ قواعد بيانات التسجيل؛ محطات المصادقة التشفيرية الآمنة.",
    applicationDate: "2023-01-10",
    registrationDate: "2023-05-20",
    validityDate: "2033-05-20",
    address: "Babylon Square, Hilla, Babylon Governorate, Iraq",
    addressAr: "ساحة بابل، الحلة، محافظة بابل، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1684540800000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "410294",
    proprietor: "TESLA, INC.",
    proprietorAr: "شركة تيسلا المحدودة",
    trademarkName: "TESLA",
    trademarkNameAr: "تيسلا",
    classNumber: 12,
    goodsServices: "Electric land vehicles, namely, electric cars, power units, chassis; batteries, superchargers and engines for electric vehicles; structural parts thereof.",
    goodsServicesAr: "مركبات برية كهربائية، وهي السيارات الكهربائية، ووحدات الطاقة، وهياكل السيارات؛ البطاريات والشواحن الفائقة ومحركات المركبات الكهربائية؛ وأجزائها الهيكلية.",
    applicationDate: "2023-03-14",
    registrationDate: "2023-09-14",
    validityDate: "2033-09-14",
    address: "3500 Deer Creek Road, Palo Alto, California, USA",
    addressAr: "٣٥٠٠ طريق دير كريك، بالو ألتو، كاليفورنيا، الولايات المتحدة الأمريكية",
    logoStyle: "stylized-text",
    updatedAt: 1694649600000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "421045",
    proprietor: "APPLE INC.",
    proprietorAr: "شركة أبل المساهمة",
    trademarkName: "APPLE",
    trademarkNameAr: "أبل",
    classNumber: 9,
    goodsServices: "Smart phones, computer hardware, digital music players, personal digital assistants, network software, operating systems, tablet computers.",
    goodsServicesAr: "الهواتف الذكية، أجهزة الكمبيوتر، مشغلات الموسيقى الرقمية، المساعدات الرقمية الشخصية، برمجيات الشبكات، أنظمة التشغيل، أجهزة الكمبيوتر اللوحية.",
    applicationDate: "2023-07-06",
    registrationDate: "2024-01-10",
    validityDate: "2034-01-10",
    address: "One Apple Park Way, Cupertino, California, USA",
    addressAr: "وان أبل بارك واي، كوبرتينو، كاليفورنيا، الولايات المتحدة الأمريكية",
    logoStyle: "stylized-text",
    updatedAt: 1704844800000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "430891",
    proprietor: "PEPSICO, INC.",
    proprietorAr: "شركة بيبسيكو المحدودة",
    trademarkName: "PEPSI-COLA",
    trademarkNameAr: "بيبسي كولا",
    classNumber: 32,
    goodsServices: "Carbonated non-alcoholic soft drinks; syrups, concentrates, powders, and preparations for making mineral and aerated waters and beverages.",
    goodsServicesAr: "مشروبات غازية غير كحولية؛ شراب، مركزات، مساحيق، ومستحضرات لصنع المياه المعدنية والغازية والمشروبات.",
    applicationDate: "2022-05-02",
    registrationDate: "2022-11-05",
    validityDate: "2032-11-05",
    address: "700 Anderson Hill Road, Purchase, New York, USA",
    addressAr: "٧٠٠ طريق أندرسون هيل، بيرتشايس، نيويورك، الولايات المتحدة الأمريكية",
    logoStyle: "stylized-text",
    updatedAt: 1667606400000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "438201",
    proprietor: "AL-RAFIDAIN PAINTS AND CHEMICAL CO",
    proprietorAr: "شركة الرافدين للأصباغ والمواد الكيماوية",
    trademarkName: "RAFIDAIN PAINTS",
    trademarkNameAr: "أصباغ الرافدين",
    classNumber: 2,
    goodsServices: "Paints, varnishes, lacquers; preservatives against rust and against deterioration of wood; colorants, mordants; raw natural resins.",
    goodsServicesAr: "الدهانات، الورنيش، واللاكيه؛ واقيات الصدأ ومنع تلف الأخشاب؛ المواد الملونة، المواد المثبتة للألوان؛ الراتنجات الطبيعية الخام.",
    applicationDate: "2023-06-18",
    registrationDate: "2023-12-18",
    validityDate: "2033-12-18",
    address: "Industrial Area East, Erbil, Iraq",
    addressAr: "المنطقة الصناعية الشرقية، أربيل، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1702857600000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "440192",
    proprietor: "AL-MAHA SEED & AGRICULTURE INT",
    proprietorAr: "شركة المها للحبوب والزراعة العالمية",
    trademarkName: "MAHA GREEN",
    trademarkNameAr: "المها الأخضر",
    classNumber: 31,
    goodsServices: "Agricultural seeds, forestry grains, fresh fruits and organic vegetables; plant seeds, natural flowers and crop seedlings.",
    goodsServicesAr: "البذور الزراعية، حبوب الغابات، الفواكه الطازجة والخضروات العضوية؛ بذور النباتات، الزهور الطبيعية وشتلات المحاصيل.",
    applicationDate: "2023-12-25",
    registrationDate: "2024-06-25",
    validityDate: "2034-06-25",
    address: "Al-Mansour Quarter, Baghdad, Iraq",
    addressAr: "حي المنصور، بغداد، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1719273600000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "448920",
    proprietor: "SINOPEC CHONGQING COIL CO.",
    proprietorAr: "شركة سينوبك تشونغتشينغ للمحامل",
    trademarkName: "SINOPEC LUBRI",
    trademarkNameAr: "سينوبك لوبري",
    classNumber: 4,
    goodsServices: "Industrial lubricants, motor oils, grease, paraffin wax, petroleum petroleum fuels and high-temperature machinery fluids.",
    goodsServicesAr: "زيوت التشحيم الصناعية، زيوت المحركات، الشحوم، شمع البارافين، وقود البترول وسوائل الآلات ذات الحرارة العالية.",
    applicationDate: "2024-08-14",
    registrationDate: "2025-02-14",
    validityDate: "2035-02-14",
    address: "Chongqing High Tech District, Chongqing, China",
    addressAr: "منطقة تشونغتشينغ للتقنيات العالية، تشونغتشينغ، الصين",
    logoStyle: "stylized-text",
    updatedAt: 1739491200000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "452097",
    proprietor: "MICROSOFT CORPORATION",
    proprietorAr: "شركة مايكروسوفت العالمية",
    trademarkName: "WINDOWS IRAQ",
    trademarkNameAr: "ويندوز العراق",
    classNumber: 42,
    goodsServices: "Cloud computing services, design of computer software, technical translation services for operating systems, networks support.",
    goodsServicesAr: "خدمات الحوسبة السحابية، تصميم برمجيات الكمبيوتر، خدمات الترجمة الفنية لأنظمة التشغيل، دعم شبكات الاتصال.",
    applicationDate: "2025-02-10",
    registrationDate: "2025-08-30",
    validityDate: "2035-08-30",
    address: "One Microsoft Way, Redmond, Washington, USA",
    addressAr: "وان مايكروسوفت واي، ريدموند، واشنطن، الولايات المتحدة الأمريكية",
    logoStyle: "stylized-text",
    updatedAt: 1756512000000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "459302",
    proprietor: "ERBIL AL-SULTAN SWEETS & CO",
    proprietorAr: "حلويات السلطان وأولاده - أربيل",
    trademarkName: "AL-SULTAN BAKLAVA",
    trademarkNameAr: "بقلاوة السلطان",
    classNumber: 30,
    goodsServices: "Pastries, traditional sweets, baklava, confectionery, sugar confectionery, and bakery flour preparations.",
    goodsServicesAr: "المعجنات، الحلويات الشرقية والتقليدية، البقلاوة، السكاكر، الحلويات السكرية، ومستحضرات دقيق المخبوزات.",
    applicationDate: "2024-05-22",
    registrationDate: "2024-11-22",
    validityDate: "2034-11-22",
    address: "60 Meter Street, Erbil, Iraq",
    addressAr: "شارع ٦٠ متري، أربيل، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1732233600000,
    status: "active",
    syncStatus: "synced"
  },
  {
    id: "462100",
    proprietor: "IRAQI AIRWAYS COMPANY",
    proprietorAr: "الشركة العامة للخطوط الجوية العراقية",
    trademarkName: "GREEN EAGLE FLYER",
    trademarkNameAr: "طائر النسر الأخضر",
    classNumber: 39,
    goodsServices: "Commercial air transport services of passengers, items and cargo; airline charter planning and travel agency booking.",
    goodsServicesAr: "خدمات النقل الجوي التجاري للمسافرين والأمتعة والبضائع؛ تخطيط الطيران العارض وحجز وكالات السفر والسياحة.",
    applicationDate: "2025-07-18",
    registrationDate: "2026-01-18",
    validityDate: "2036-01-18",
    address: "Baghdad International Airport Area, Baghdad, Iraq",
    addressAr: "منطقة مطار بغداد الدولي، بغداد، العراق",
    logoStyle: "stylized-text",
    updatedAt: 1768694400000,
    status: "active",
    syncStatus: "synced"
  }
];
